@baseUrl=http://localhost:3001/jobs
@profileId=1

### get unpaid jobs
GET {{baseUrl}}/unpaid HTTP/1.1
profile_id : {{profileId}}

### pay job
POST {{baseUrl}}/2/pay HTTP/1.1
profile_id : {{profileId}}
