@baseUrl=http://localhost:3001/contracts
@profileId=1

### get contract by id
GET {{baseUrl}}/1 HTTP/1.1
profile_id : {{profileId}}

### return not found since this profile don't own contract 3
GET {{baseUrl}}/3 HTTP/1.1
profile_id : {{profileId}}

### get all non terminated contracts
GET {{baseUrl}} HTTP/1.1
profile_id : 6
