@baseUrl=http://localhost:3001/balances
@profileId=2

### try to deposit more thant the limit, should return bad request with an error message
POST {{baseUrl}}/deposit/{{profileId}} HTTP/1.1
profile_id : {{profileId}}
Content-Type: application/json

{
    "amount": 100
}

### successfull deposit
POST {{baseUrl}}/deposit/{{profileId}} HTTP/1.1
profile_id : 4
Content-Type: application/json

{
    "amount": 10
}